/// Each new term in the Fibonacci sequence is generated by
///  adding the previous two terms. By starting with 1 and 2,
///  the first 10 terms will be:
/// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

/// By considering the terms in the Fibonacci sequence whose
/// values do not exceed four million, find the sum of the even-valued terms.

// TODO: the iterative method
import 'fibonacciNumbersGenerator.dart';

void main() {
  List<int> fibonacciNumbers = fibonacciNumbersGenerator(4000000);
  int sum = 0;

  /// After observing the fibonnaci numbers you result this pattern:
  /// [odd, odd, even, odd, odd, even ...]
  /// Because the two first element are odd numbers & depending on this
  /// rules:
  /// odd + odd = even,
  /// even + odd = odd,
  /// The pattern will be created

  for (int i = 2; i < fibonacciNumbers.length; i += 3) {
    sum += fibonacciNumbers[i];
  }
  print(sum);
}
